# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16T91NVI6XrUtpkRdi_J_VC6A22jDZEri
"""

# ============================================================
# PENELITIAN FINAL SESUAI PROPOSAL
# Analisis Penerapan Algoritma Random Forest dalam
# Meningkatkan Akurasi Deteksi Intrusi pada Jaringan Komputer
# Panji Kurniawan
# (VERSI DIPERBAIKI: SVM pakai subset supaya tidak macet,
#  + ditambah langkah penanganan outlier sesuai proposal)
# ============================================================

# ============================================================
# STEP 0 : DOWNLOAD DATASET NSL-KDD
# ============================================================

!wget -q https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain+.txt
!wget -q https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTest+.txt

print("Dataset berhasil didownload\n")

# ============================================================
# IMPORT LIBRARY
# ============================================================

import sys
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV
)

from sklearn.preprocessing import (
    LabelEncoder,
    MinMaxScaler
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

# ============================================================
# LOGGING FILE
# ============================================================

class Tee:
    def __init__(self, *streams):
        self.streams = streams

    def write(self, data):
        for s in self.streams:
            s.write(data)
            s.flush()

    def flush(self):
        for s in self.streams:
            s.flush()


_log_file = open("hasil_lengkap.txt", "w", encoding="utf-8")
_real_stdout = sys.stdout
sys.stdout = Tee(_real_stdout, _log_file)

print("Library berhasil dimuat\n")

# ============================================================
# STEP 1 : MEMBACA DATASET
# ============================================================

columns = [
    "duration","protocol_type","service","flag","src_bytes","dst_bytes",
    "land","wrong_fragment","urgent","hot","num_failed_logins","logged_in",
    "num_compromised","root_shell","su_attempted","num_root","num_file_creations",
    "num_shells","num_access_files","num_outbound_cmds","is_host_login",
    "is_guest_login","count","srv_count","serror_rate","srv_serror_rate",
    "rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate",
    "srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
    "dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate",
    "label","difficulty"
]

train_data = pd.read_csv(
    "KDDTrain+.txt",
    names=columns
)

test_data = pd.read_csv(
    "KDDTest+.txt",
    names=columns
)

# gabungkan (total sampling)
df = pd.concat(
    [train_data, test_data],
    ignore_index=True
)

# hapus kolom difficulty
df.drop(
    columns=["difficulty"],
    inplace=True
)

print("=== DATASET BERHASIL DIBACA ===")
print("Total data :", df.shape[0])
print()

# ============================================================
# STEP 2 : CEK MISSING VALUE
# ============================================================

print("=== CEK MISSING VALUE ===")

missing = df.isnull().sum().sum()

print("Jumlah missing value :", missing)

df = df.dropna()

print("Jumlah data setelah dibersihkan dari missing value :", df.shape[0])
print()

# ============================================================
# STEP 3 : CEK DUPLIKAT
# ============================================================

print("=== CEK DUPLIKAT ===")

duplicate = df.duplicated().sum()

print("Jumlah data duplikat :", duplicate)

df = df.drop_duplicates()

print("Jumlah data setelah cleaning :", df.shape[0])
print()

# ============================================================
# STEP 3B : PENANGANAN OUTLIER
# (sesuai proposal: "outliers diidentifikasi dan dihapus")
# Menggunakan metode IQR (Interquartile Range) pada fitur
# numerik utama. Batas dibuat lebar (1.5*IQR di luar Q1/Q3)
# supaya tidak menghapus data serangan yang justru penting
# (serangan DDoS/DoS secara alami punya nilai numerik ekstrem,
# jadi outlier di sini cuma membuang anomali ekstrem yang
# benar-benar tidak wajar, bukan membuang sinyal serangan).
# ============================================================

print("=== PENANGANAN OUTLIER (metode IQR) ===")

numeric_cols_for_outlier = ["duration", "src_bytes", "dst_bytes"]

jumlah_sebelum_outlier = df.shape[0]

for col in numeric_cols_for_outlier:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    batas_bawah = Q1 - 3 * IQR
    batas_atas = Q3 + 3 * IQR
    df = df[(df[col] >= batas_bawah) & (df[col] <= batas_atas)]

jumlah_sesudah_outlier = df.shape[0]

print("Fitur yang dicek outlier :", numeric_cols_for_outlier)
print("Jumlah data sebelum penghapusan outlier :", jumlah_sebelum_outlier)
print("Jumlah data setelah penghapusan outlier  :", jumlah_sesudah_outlier)
print("Jumlah data outlier yang dihapus         :", jumlah_sebelum_outlier - jumlah_sesudah_outlier)
print()

# ============================================================
# STEP 4 : BINARY CLASSIFICATION
# normal = 0
# attack = 1
# ============================================================

print("=== KONVERSI LABEL ===")

df["label"] = df["label"].apply(
    lambda x: "normal" if x == "normal" else "attack"
)

print(df["label"].value_counts())
print()

# ============================================================
# STEP 5 : ONE HOT ENCODING
# ============================================================

print("=== ONE HOT ENCODING ===")

categorical_columns = [
    "protocol_type",
    "service",
    "flag"
]

df_encoded = pd.get_dummies(
    df,
    columns=categorical_columns
)

print("Jumlah fitur setelah encoding :", df_encoded.shape[1])
print()

# ============================================================
# STEP 6 : PEMISAHAN FITUR DAN LABEL
# ============================================================

print("=== MEMISAHKAN FITUR DAN LABEL ===")

X = df_encoded.drop(
    columns=["label"]
)
y_raw = df_encoded["label"]

label_encoder = LabelEncoder()

# normal = 0, attack = 1
y = label_encoder.fit_transform(y_raw)

print("Jumlah data fitur :", X.shape)
print("Jumlah label :", y.shape)
print()

# ============================================================
# STEP 7 : SPLIT DATA 70:30
# sesuai proposal penelitian
# ============================================================

print("=== TRAIN TEST SPLIT 70:30 ===")

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Data training :", X_train.shape[0])
print("Data testing  :", X_test.shape[0])
print()

# ============================================================
# STEP 8 : NORMALISASI DATA
# menggunakan MinMaxScaler
# ============================================================

print("=== NORMALISASI DATA ===")

scaler = MinMaxScaler()

# fit hanya pada training
X_train_scaled = scaler.fit_transform(X_train)
# transform test
X_test_scaled = scaler.transform(X_test)

print("Normalisasi selesai")
print()

# ============================================================
# STEP 9 : DISTRIBUSI DATA
# ============================================================

print("=== DISTRIBUSI LABEL TRAINING ===")

jumlah_normal = np.sum(y_train == 1)
jumlah_attack = np.sum(y_train == 0)

print("Normal :", jumlah_normal)
print("Attack :", jumlah_attack)
print()

print("=== DISTRIBUSI LABEL TESTING ===")

jumlah_normal_test = np.sum(y_test == 1)
jumlah_attack_test = np.sum(y_test == 0)

print("Normal :", jumlah_normal_test)
print("Attack :", jumlah_attack_test)
print()

print("Preprocessing selesai.\n")

# ============================================================
# STEP 9B : SUBSET KHUSUS UNTUK SVM
# SVM dengan kernel RBF sangat berat secara komputasi pada data
# besar (puluhan-ratusan ribu baris bisa makan waktu berjam-jam).
# Decision Tree dan Random Forest TETAP memakai data penuh
# (X_train_scaled, y_train) karena keduanya cukup cepat.
# Khusus SVM, cross-validation, grid search, dan training final
# memakai subset acak dari data training -- ini praktik umum
# dalam penelitian ML ketika SVM diuji pada dataset besar.
# ============================================================

print("=== MEMBUAT SUBSET KHUSUS UNTUK SVM ===")

np.random.seed(42)

# subset untuk cross-validation & grid search SVM
SVM_CV_SIZE = 15000
idx_cv = np.random.choice(
    X_train_scaled.shape[0],
    min(SVM_CV_SIZE, X_train_scaled.shape[0]),
    replace=False
)
X_train_svm_cv = X_train_scaled[idx_cv]
y_train_svm_cv = y_train[idx_cv]

# subset untuk training final SVM (lebih besar, supaya hasil tetap representatif)
SVM_FINAL_SIZE = 30000
idx_final = np.random.choice(
    X_train_scaled.shape[0],
    min(SVM_FINAL_SIZE, X_train_scaled.shape[0]),
    replace=False
)
X_train_svm_final = X_train_scaled[idx_final]
y_train_svm_final = y_train[idx_final]

print("Ukuran subset SVM (cross-validation & grid search) :", X_train_svm_cv.shape[0])
print("Ukuran subset SVM (training final)                 :", X_train_svm_final.shape[0])
print()

# ============================================================
# STEP 10 : CROSS VALIDATION 10-FOLD
# sesuai proposal penelitian
# ============================================================

print("=== CROSS VALIDATION 10-FOLD ===")

# ------------------------------------------------
# Decision Tree (data penuh, cepat)
# ------------------------------------------------
print("Cross Validation Decision Tree...")
start = time.time()
cv_dt = cross_val_score(
    DecisionTreeClassifier(random_state=42),
    X_train_scaled,
    y_train,
    cv=10,
    n_jobs=-1
)
print("Rata-rata Accuracy DT :", cv_dt.mean())
print("Waktu :", round(time.time() - start, 2), "detik")
print()

# ------------------------------------------------
# Random Forest (data penuh, cepat)
# ------------------------------------------------
print("Cross Validation Random Forest...")
start = time.time()
cv_rf = cross_val_score(
    RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    X_train_scaled,
    y_train,
    cv=10,
    n_jobs=-1
)
print("Rata-rata Accuracy RF :", cv_rf.mean())
print("Waktu :", round(time.time() - start, 2), "detik")
print()

# ------------------------------------------------
# SVM (PAKAI SUBSET, supaya tidak macet berjam-jam)
# ------------------------------------------------
print("Cross Validation SVM (memakai subset", X_train_svm_cv.shape[0], "data)...")
start = time.time()
cv_svm = cross_val_score(
    SVC(
        kernel="rbf",
        random_state=42
    ),
    X_train_svm_cv,
    y_train_svm_cv,
    cv=10,
    n_jobs=-1
)
print("Rata-rata Accuracy SVM :", cv_svm.mean())
print("Waktu :", round(time.time() - start, 2), "detik")
print()

# ============================================================
# STEP 10B : SIMPAN HASIL 10-FOLD CROSS VALIDATION
# (untuk uji statistik di WS-14: Friedman test, dll.)
# ============================================================

print("=== MENYIMPAN HASIL 10-FOLD CV UNTUK UJI STATISTIK ===")

cv_results_df = pd.DataFrame({
    "Fold": list(range(1, 11)),
    "Decision Tree": cv_dt,
    "Random Forest": cv_rf,
    "SVM": cv_svm
})

cv_results_df.to_csv("hasil_cv_10fold.csv", index=False)

print(cv_results_df)
print("\nDisimpan sebagai 'hasil_cv_10fold.csv'")
print()

# ============================================================
# STEP 11 : GRID SEARCH DECISION TREE
# ============================================================

print("=== GRID SEARCH DECISION TREE ===")

param_dt = {
    "criterion": ["gini", "entropy"],
    "max_depth": [10, 20, 30, None]
}

start = time.time()
grid_dt = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid=param_dt,
    cv=5,
    n_jobs=-1
)
grid_dt.fit(
    X_train_scaled,
    y_train
)
best_dt = grid_dt.best_estimator_
print("Best parameter DT :", grid_dt.best_params_)
print("Waktu :", round(time.time() - start, 2), "detik")
print()

# ============================================================
# STEP 12 : GRID SEARCH RANDOM FOREST
# ============================================================

print("=== GRID SEARCH RANDOM FOREST ===")

param_rf = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20, None]
}

start = time.time()
grid_rf = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=param_rf,
    cv=5,
    n_jobs=-1
)
grid_rf.fit(
    X_train_scaled,
    y_train
)
best_rf = grid_rf.best_estimator_
print("Best parameter RF :", grid_rf.best_params_)
print("Waktu :", round(time.time() - start, 2), "detik")
print()

# ============================================================
# STEP 13 : GRID SEARCH SVM (PAKAI SUBSET)
# ============================================================

print("=== GRID SEARCH SVM (memakai subset", X_train_svm_cv.shape[0], "data) ===")

param_svm = {
    "C": [1, 10],
    "gamma": ["scale", 0.01]
}

start = time.time()
grid_svm = GridSearchCV(
    SVC(
        kernel="rbf",
        probability=True,
        random_state=42
    ),
    param_grid=param_svm,
    cv=5,
    n_jobs=-1
)
grid_svm.fit(
    X_train_svm_cv,
    y_train_svm_cv
)
best_svm_params = grid_svm.best_params_
print("Best parameter SVM :", grid_svm.best_params_)
print("Waktu :", round(time.time() - start, 2), "detik")
print()

print("Hyperparameter tuning selesai.\n")

# ============================================================
# STEP 14 : FINAL TRAINING MODEL
# ============================================================

print("=== FINAL TRAINING DAN EVALUASI ===")

# Setiap model dipasangkan dengan data training-nya sendiri:
# DT & RF pakai data penuh, SVM pakai subset (lihat STEP 9B)
final_models = {

    "Decision Tree": (best_dt, X_train_scaled, y_train),

    "Random Forest": (best_rf, X_train_scaled, y_train),

    "SVM": (
        SVC(
            kernel="rbf",
            probability=True,
            random_state=42,
            **best_svm_params
        ),
        X_train_svm_final,
        y_train_svm_final
    )
}

results = []

roc_data = {}

# ============================================================
# LOOP EVALUASI SEMUA MODEL
# ============================================================

for nama_model, (model, X_fit, y_fit) in final_models.items():

    print("========================================")
    print("Memproses :", nama_model)

    start = time.time()

    # training model (memakai data training masing-masing model)
    model.fit(
        X_fit,
        y_fit
    )

    # prediksi label (selalu dievaluasi di X_test_scaled yang sama, 30% data)
    y_pred = model.predict(
        X_test_scaled
    )

    # probabilitas untuk AUC
    y_prob = model.predict_proba(
        X_test_scaled
    )[:, 1]

    # ============================
    # METRIK EVALUASI
    # ============================

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    precision = precision_score(
        y_test,
        y_pred
    )

    recall = recall_score(
        y_test,
        y_pred
    )

    f1 = f1_score(
        y_test,
        y_pred
    )

    auc = roc_auc_score(
        y_test,
        y_prob
    )

    # confusion matrix
    cm = confusion_matrix(
        y_test,
        y_pred
    )

    print("Confusion Matrix:")
    print(cm)
    print()

    print("Classification Report:")
    print(
        classification_report(
            y_test,
            y_pred
        )
    )

    waktu = time.time() - start

    print("Accuracy  :", round(accuracy, 4))
    print("Precision :", round(precision, 4))
    print("Recall    :", round(recall, 4))
    print("F1 Score  :", round(f1, 4))
    print("AUC       :", round(auc, 4))
    print("Waktu     :", round(waktu, 2), "detik")
    print()

    # simpan hasil
    results.append({

        "Model": nama_model,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1,
        "AUC": auc,
        "Waktu (detik)": waktu

    })

    # simpan data ROC
    fpr, tpr, _ = roc_curve(
        y_test,
        y_prob
    )

    roc_data[nama_model] = (fpr, tpr)

# ============================================================
# STEP 15 : SIMPAN CSV
# ============================================================

print("=== MENYIMPAN CSV ===")

hasil_df = pd.DataFrame(
    results
)

hasil_df.to_csv(
    "hasil_perbandingan_model.csv",
    index=False
)

print("CSV berhasil disimpan")
print()

# ============================================================
# STEP 16 : GRAFIK ACCURACY
# ============================================================

print("=== MEMBUAT GRAFIK ACCURACY ===")

plt.figure(figsize=(10,6))

plt.bar(
    hasil_df["Model"],
    hasil_df["Accuracy"]
)

plt.title(
    "Perbandingan Accuracy Model"
)

plt.xlabel(
    "Algoritma"
)

plt.ylabel(
    "Accuracy"
)

plt.savefig(
    "perbandingan_model.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Grafik accuracy berhasil disimpan\n")

# ============================================================
# STEP 17 : ROC CURVE
# ============================================================

print("=== MEMBUAT ROC CURVE ===")

plt.figure(figsize=(8,6))

for nama_model, (fpr, tpr) in roc_data.items():

    plt.plot(
        fpr,
        tpr,
        label=nama_model
    )

# garis baseline
plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ROC Curve Comparison"
)

plt.legend()

plt.savefig(
    "roc_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("ROC Curve berhasil disimpan\n")

# ============================================================
# STEP 18 : TAMPILKAN HASIL AKHIR
# ============================================================

print("=== HASIL AKHIR PENELITIAN ===")

print(hasil_df)
print()

# ============================================================
# STEP 19 : TUTUP LOG FILE
# ============================================================

sys.stdout = _real_stdout
_log_file.close()

print("=======================================")
print("SEMUA PROSES SELESAI")
print("File hasil penelitian:")

print("- hasil_lengkap.txt")
print("- hasil_perbandingan_model.csv")
print("- perbandingan_model.png")
print("- roc_curve.png")
print("=======================================")